#!/bin/bash

HOME="/home/scillidan"
MYMPV="$HOME/Github/my_mpv"
MPV_DIR="$HOME/.config/mpv"
SRC="$HOME/Git/mpv_sources"
DL="$HOME/Git/mpv_downloads"
IND="input"
INCLD="include"
INCLOD="include-opts"
SD="scripts"
SOD="scripts-opts"
SMD="script-modules"
MYSD="$MYMPV/$SD"
MYSOD="$MYMPV/$SOD"
CD_VIDEO="$MYMPV/cd_video"
CD_STREAM="$MYMPV/cd_stream"
CD_MUSIC="$MYMPV/cd_music"
CD_MANGA="$MYMPV/cd_manga"
CD_EDIT="$MYMPV/cd_edit"
export DL SRC MYMPV IND INCLD INCLOD SD SOD SMD MYSD MYSOD CD_VIDEO CD_STREAM CD_MUSIC CD_MANGA CD_EDIT MPV_DIR